### PR TITLE
G0.215 - Resolve deprecations in failed test.

### LINKED ISSUE #214: G0.214 - Resolve deprecations and updated Tripal Importer service dependencies
### Branch

g0.214-addressDeprecations

### Groups

Group 0 - General

### Describe

Kernel/Functional tests in this repo are failing due to the following:
1. Kernel test classes must specify the **#[RunTestsInSeparateProcesses]** attribute, not doing so is deprecated in drupal:11.3.0
2. TripalImporterBase::__construct() without the **$messenger** argument is deprecated in tripal 4.0.0-alpha3 and it will be required in tripal:4.1.0.
3. /var/www/drupal/web/modules/contrib/tripal/tripal/src/TripalImporter/TripalImporterBase.php:228
Calling Drupal\tripal\TripalImporter\TripalImporterBase::__construct() without the **$logger** argument is deprecated in tripal 4.0.0-alpha3 and it will be required in tripal:4.1.0.
4. TripalImporterBase.php:235
Calling Drupal\tripal\TripalImporter\TripalImporterBase::__construct() without the **$fileretriever** argument is deprecated in tripal 4.0.0-alpha3 and it will be required in tripal:4.1.0.
5. TripalImporterBase.php:242
Calling Drupal\tripal\TripalImporter\TripalImporterBase::__construct() without the **$publish_manager** argument is deprecated in tripal 4.0.0-alpha3 and it will be required in tripal:4.1.0.
6. Renderer::renderPlain() is deprecated in drupal:10.3.0 and is removed from drupal:12.0.0. Instead, you should use ::renderInIsolation().
7. Applied #[IgnoreDeprecations] in some tests. Inspect the code base and not just implement this attribute.

### Design

Resolve issues as prescribed.

### PR DESCRIPTION
**Pull request by reynoldtan**
**Issue #214**

## Motivation

Test are failing due to deprecation. See issue.

## What does this PR do?
*Please describe each things this PR does. For example, a PR may 1) solve a specific bug, 2) create an automated test to ensure it doesn't return.*

1. Add **#[RunTestsInSeparateProcesses]** attribute to all kernel and functional tests.
2. Resolve deprecation notices that cause the test to fail. Failed test includes solutions to implement. Deprecations - Request::get(), $escape parameter in str_getcsv(), and renderPlain().
3. In Tripal Importer, add to the constructor additional required services.
4. Setup new Hook class with backward compatibility support using #[LegacyHook] attribute.
5. Create services for each hook in services.yml.
6. Remove annotations in validator plugin and importers.
7. Apply ignore deprecation attribute only when necessary and after verifying the source code. Below is a list of test that has **#[IgnoreDeprecations]** attribute and the target deprecation.

**Phenotypes:**
Entity
1. PhenodataBackupFormTest
2. PhenodataBackupListTest

- Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider::getEntityTypeIdKeyType() is deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. To determine if an entity type has an integer ID key, use \Drupal\Core\Entity\EntityTypeInterface::hasIntegerId()

Form
1. PhenoExperimentConfigurationFormTest
2. PhenoExperimentTraitSelectorFormTest

- Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider::getEntityTypeIdKeyType() is deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. To determine if an entity type has an integer ID key, use \Drupal\Core\Entity\EntityTypeInterface::hasIntegerId()

- Using @FieldType annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldType attribute instead. See https://www.drupal.org/node/3395575

- Using @FieldWidget annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldWidget attribute instead. See https://www.drupal.org/node/3395575

- Using @FieldFormatter annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldFormatter attribute instead. See https://www.drupal.org/node/3395575

- Providing a file for theme hook horizontal_tabs is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500

- Providing template_preprocess_horizontal_tabs() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125

- Providing a file for theme hook field_group_html_element is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500

- Providing template_preprocess_field_group_html_element() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125

---

**PhenoShare**
TripalImporter
1. ShareImporterFormTest
2. ShareImporterFormValidateTest

- Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider::getEntityTypeIdKeyType() is deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. To determine if an entity type has an integer ID key, use \Drupal\Core\Entity\EntityTypeInterface::hasIntegerId()

---

**Phenotypes, PhenoShare, and PhenoCollect**
Functional
1. InstallTest

- Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider::getEntityTypeIdKeyType() is deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. To determine if an entity type has an integer ID key, use \Drupal\Core\Entity\EntityTypeInterface::hasIntegerId() 
- Not supporting attribute discovery in Drupal\field_group\FieldGroupFormatterPluginManager is deprecated in drupal:11.2.0 and is removed from drupal:12.0.0. Provide an Attribute class and an Annotation class for BC. See https://www.drupal.org/node/3395582

- Using @FieldType annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldType attribute instead. See https://www.drupal.org/node/3395575

- Using @FieldFormatter annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldFormatter attribute instead. See https://www.drupal.org/node/3395575

- Providing a file for theme hook horizontal_tabs is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500

- Providing template_preprocess_horizontal_tabs() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125

- Providing a file for theme hook field_group_html_element is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500

- Providing template_preprocess_field_group_html_element() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125

## Testing

Ensure continued success of **all** tests.
Screenshot 2026-02-24 at 9 35 44 AM
Screenshot 2026-02-24 at 9 36 27 AM

### CODE REVIEW

File: trpcultivate_phenotypes/tests/src/Kernel/Validators/FakeValidators/BasicallyBase.php [hunk 1]
```diff
@@ -22,6 +23,7 @@
    validator_name: new TranslatableMarkup('Basically Base Validator'),
    input_types: ['header-row', 'data-row']
  )]
+#[RunTestsInSeparateProcesses]
```
Comment (laceysanderson) [inline trpcultivate_phenotypes/tests/src/Kernel/Validators/FakeValidators/BasicallyBase.php]: Fake validators are not tests and should not need/have this annotation. Did you get an error when you didn't include it or did autopilot take over?

File: trpcultivate_phenotypes/tests/src/Traits/PhenotypeImporterTestTrait.php [hunk 2]
```diff
@@ -3,10 +3,12 @@
 namespace Drupal\Tests\trpcultivate_phenotypes\Traits;
 
 use Drupal\tripal_chado\Database\ChadoConnection;
+use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;
 
 /**
  * Phenotypes test trait.
  */
+#[RunTestsInSeparateProcesses]
```
Comment (laceysanderson) [inline trpcultivate_phenotypes/tests/src/Traits/PhenotypeImporterTestTrait.php]: Test traits are not tests themselves and as such should not need this attribute.

File: trpcultivate_phenotypes/tests/src/Kernel/Services/Traits/ValidTraitTest.php [hunk 3]
```diff
@@ -665,7 +669,9 @@ public function testTraitsServiceGetters() {
 
     // Set accessible for protected method.
     $method = $reflection->getMethod('getPhenoCvTerm');
-    $method->setAccessible(TRUE);
+    if (method_exists($method, 'setAccessible')) {
+      $method->setAccessible(TRUE);
+    }
```
Comment (laceysanderson) [inline trpcultivate_phenotypes/tests/src/Kernel/Services/Traits/ValidTraitTest.php]: This should be removed entirely. According to the manual this is not needed after 8.1. Specifically, ["Note: As of PHP 8.1.0, calling this method has no effect; all methods are invokable by default."](https://www.php.net/manual/en/reflectionmethod.setaccessible.php).

**Review by laceysanderson — CHANGES_REQUESTED** [review]
See inline comments from code review.

Also, we are still seeing a lot of phpunit deprecations in tests: https://github.com/TripalCultivate/TripalCultivate-Phenotypes/actions/runs/22580161198/job/65409753198#step:3:385. These should also be resolved.

Note: I still need to further think about the use of `#[IgnoreDeprecations]` so expect a comment on that later today.

File: trpcultivate_phenotypes/tests/src/Kernel/Validators/FakeValidators/BasicallyBase.php (hunk 1 above)
Comment (reynoldtan) [reply trpcultivate_phenotypes/tests/src/Kernel/Validators/FakeValidators/BasicallyBase.php]: I added the annotation based on my understanding that this is a part of the test - No autopilot involved. Let's keep the discussion focused on the implementation details.

Addressed in: https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/215/commits/d2b590f5a29d07b23f2a7d76c602a7a8a2da8946

File: trpcultivate_phenotypes/tests/src/Traits/PhenotypeImporterTestTrait.php (hunk 2 above)
Comment (reynoldtan) [reply trpcultivate_phenotypes/tests/src/Traits/PhenotypeImporterTestTrait.php]: Addressed in https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/215/commits/d2b590f5a29d07b23f2a7d76c602a7a8a2da8946

File: trpcultivate_phenotypes/tests/src/Kernel/Services/Traits/ValidTraitTest.php (hunk 3 above)
Comment (reynoldtan) [reply trpcultivate_phenotypes/tests/src/Kernel/Services/Traits/ValidTraitTest.php]: Removed in https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/215/commits/d2b590f5a29d07b23f2a7d76c602a7a8a2da8946

File: trpcultivate_phenotypes/tests/src/Kernel/Validators/FakeValidators/BasicallyBase.php (hunk 1 above)
Comment (laceysanderson) [reply trpcultivate_phenotypes/tests/src/Kernel/Validators/FakeValidators/BasicallyBase.php]: Sorry I wasn't clear --this annotation should only be in test classes. So none of the Fake validators or any test traits.

**Comment by laceysanderson** [comment]
Regarding `#[IgnoreDeprecations]`, this should only be added to tests that are testing a legacy/deprecated function. More specifically, if we deprecate a service `dog::bark()` in our own code, then any test for `dog::bark()` would have `#[IgnoreDeprecations]` added to it.

We do not have any of these cases in the current deprecations. Instead these are all deprecations related to external modules and our use of them. As such, we do not want to use that tag anywhere in this PR.

> Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider::getEntityTypeIdKeyType() is deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. To determine if an entity type has an integer ID key, use \Drupal\Core\Entity\EntityTypeInterface::hasIntegerId() 

This was caused by Tripal core and has since been solved.

>  Providing a file for theme hook horizontal_tabs is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500
> Providing template_preprocess_horizontal_tabs() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125
> Providing a file for theme hook field_group_html_element is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500
> Providing template_preprocess_field_group_html_element() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125
> Providing a file for theme hook horizontal_tabs is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500
> Providing template_preprocess_horizontal_tabs() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125

The above are being explored in https://github.com/TripalCultivate/TripalCultivate/issues/105 and should remain unfixed in phenotypes until we find a solution.

> Not supporting attribute discovery in Drupal\field_group\FieldGroupFormatterPluginManager is deprecated in drupal:11.2.0 and is removed from drupal:12.0.0. Provide an Attribute class and an Annotation class for BC. See https://www.drupal.org/node/3395582

The above is being explored in https://github.com/TripalCultivate/TripalCultivate/issues/106 and should remain unfixed in phenotypes until we find a solution.

>  Using @FieldType annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldType attribute instead. See https://www.drupal.org/node/3395575
> Using @FieldFormatter annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldFormatter attribute instead. See https://www.drupal.org/node/3395575
> Using @FieldWidget annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldWidget attribute instead. See https://www.drupal.org/node/3395575

The above are being resolved in https://github.com/TripalCultivate/TripalCultivate/issues/104 and should remain unfixed in phenotypes until we find a solution.

**Comment by reynoldtan** [comment]
Below are outstanding deprecations (4 items) from removing the #[IgnoreDeprecations].

- Not supporting attribute discovery in Drupal\field_group\FieldGroupFormatterPluginManager is deprecated in drupal:11.2.0 and is removed from drupal:12.0.0. Provide an Attribute class and an Annotation class for BC. See https://www.drupal.org/node/3395582

- AttributeDiscoveryWithAnnotations.php:98
Using @FieldType annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldType attribute instead. See https://www.drupal.org/node/3395575

- AttributeDiscoveryWithAnnotations.php:98
Using @FieldFormatter annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldFormatter attribute instead. See https://www.drupal.org/node/3395575

- AttributeDiscoveryWithAnnotations.php:98
Using @FieldWidget annotation for plugin with ID markup is deprecated and is removed from drupal:13.0.0. Use a Drupal\Core\Field\Attribute\FieldWidget attribute instead. See https://www.drupal.org/node/3395575

**Comment by laceysanderson** [comment]
Fixes for the referenced 105 and 106 are now available in this PR.

File: trpcultivate_phenotypes/tests/src/Kernel/Validators/FakeValidators/BasicallyBase.php (hunk 1 above)
Comment (laceysanderson) [reply trpcultivate_phenotypes/tests/src/Kernel/Validators/FakeValidators/BasicallyBase.php]: Now complete ✅

**Review by laceysanderson — APPROVED** [review]
✅ Previous concern addressed
✅ Reconfirmed on most recent automated tests.

This is ready to merge!
