### PR TITLE
G0.150 Implement Other Validators into Importer Share

### LINKED ISSUE #149: G0.149 Implement Available Validators in Base into Importer Share
### Branch

g0.149-ImplementMoreValidators

### Groups

_No response_

### Describe

Implement available validator in Base into Importer Share

### Design

Update form validate and configure validators methods. Implement process validation message and return general validation message without any processing.

### LINKED ISSUE #155: [Bug] Share importer: Empty data file incorrectly collapses validation stage
### Drupal Version

11.2

### Tripal Version

4.x dev (most recent commit)

### Module Version

4.x dev (most recent commit)

### Site Operating System

Debian Linux

### Installation Method

TripalDocker docker

### Observations

When uploading a data file containing only a header line, I observed that the "Stage 1 : Upload Data file" is highlighted green and collapsed after validation despite a red error message at the top indicating that validation failed.
screenshot

When I manually expanded the stage 1 accordion, it became clear that the validation did catch this as shown in the following screenshot. Furthermore, it appears in the code that formValidate is correctly catching the case where we have todo's and no failures and understanding this is not a pass (hense the error message).
screenshot

### Expected Behaviour

I expect for "Stage 1: Upload data file" to remain open and not completed so that users see that there is a problem and can confirm what is it. With the window open they will see that "Required cells contain a value" could not be checked and as such will hopefully look at their file ;-p

It might be even more helpful to have a more clear statement like "Your file does not contain any data" to really make it obvious 🤔 

### Steps to Reproduce

1. Create a Research Experiment and an organism
2. Configure the phenotypes module to work with this organism by going to Tripal > Extensions > Phenotypes > Ontology Configuration.
3. Link the research experiment and organism genus using the following commands in Execute php or drush php:cli
```php
$m = \Drupal::service('trpcultivate_phenotypes.genus_project');
$m->setGenusToProject(REPLACE WITH PROJECT ID, REPLACE WITH GENUS, TRUE);
```
4. Go to the phenotypic open science (i.e. share) data importer listed at Tripal > Data Loaders and enter the experiment and genus you set up earlier. Also upload a data file with header and no data and click "Validate Data file".
5. You should observe the behaviour described above.

### PR DESCRIPTION
**Pull request by reynoldtan**
**Issue #149 Implement Available Validators in Base into Importer Share**

## Motivation

Implement the following validators into Importer Share:

- [x] Project genus match
- [x] Valid Data File
- [x] Valid Delimited File
- [x] Valid Header
- [x] Empty Cell

Upcoming:

- [ ] Column Combination Values are unique (for construction).
- [ ] Germplasm Name Exists (render array not determined).

Notes:
1. Methods contained in the 'Begin process validation message' and 'End process validation message' delimiters are also in Traits Importer with the exception of processProjectGenusMatchFailures().

## What does this PR do?
*Please describe each things this PR does. For example, a PR may 1) solve a specific bug, 2) create an automated test to ensure it doesn't return.*

1. Setup configureValidators() to implement the validators mentioned.
3. Update formValidate() method validation logic to apply validators mentioned.
4. Implemented processValidationMessage() (as defined in Trait Importer).
5. Implement each validator process failure method (as defined in Trait Importer).
6. Implement checkValidationStatusArray() method (as defined in Trait Importer).
7. Setup automated test with test file scenario similar to test scenario in Trait Importer validation test.
8. Create file fixtures.

### Automated Testing
*Please describe each automated test this PR creates and provide a list of the assertions it makes using casual language.*
*Do not just say things like "asserts the array is not empty" but rather say "Ensures that the return value of method X with these parameters is not an empty array".*

ClassName->testShareImporterFormValidateStage1
- Test when no project was provided.
- Test not the genus the project was paired with.
- Test a non-existent project.
- Test a project that was not paired with a genus.
- File is empty
- Header is improperly delimited, with proper data rows.
- Data row of file is improperly delimited.
- Contains correct header but no data.
- Contains incorrect header and one line of correct data.
- Contains correct header and one line of correct data. 3rd line has an empty value in Replicate column.
- Contains correct header and one line of correct data. 3rd line has empty line and 4th line has empty value in Replicate column.

### Manual Testing
*Describe in detail how someone should manually test this functionality.*
*Make sure to include whether they need to build a docker from scratch, create any records, etc.*

In a fully setup clone:

1. Create a test project and an organism.
2. Configure Trait, Method, Unit and DB of the genus in my clone/admin/tripal/extension/tripal-cultivate/phenotypes/ontology
3. After configuring the genus, pair the project and genus.
```
// Into devel/php
$m = \Drupal::service('trpcultivate_phenotypes.genus_project');
$m->setGenusToProject(REPLACE WITH PROJECT ID, REPLACCE WITH GENUS, TRUE);

```
4. Access the Phenotypes Share Importer page my clone/admin/tripal/loaders/trpcultivate-phenotypes-share-importer
5. Test the project and provide the test file fixtures in Share tests directory.

### CODE REVIEW

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 1]
```diff
@@ -273,21 +268,59 @@ public function configureValidators(array $form_values, string $file_mime_type)
...
+    $validators['file']['valid_data_file'] = $instance;
+
+    // -----------------------------------------------------
+    // Raw row level
+    // - File rows are properly delimited
+    $instance = $this->service_validatorPluginManager->createInstance('valid_delimited_file');
+    // Count the number of columns and configure it for this validator. We want
+    // this number to be strict = TRUE, thus no extra columns are allowed.
+    $num_columns = count($this->headers);
+    $instance->setExpectedColumns($num_columns, TRUE);
```
Comment (laceysanderson) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]: I don't think we do want this to be strict... Extra columns are allowed for the trait measurements, right?

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 2]
```diff
@@ -273,21 +268,59 @@ public function configureValidators(array $form_values, string $file_mime_type)
...
+    $validators['raw-row']['valid_delimited_file'] = $instance;
+
+    // -----------------------------------------------------
+    // Header Level
+    // - All column headers match expected header format
+    $instance = $this->service_validatorPluginManager->createInstance('valid_headers');
+    // Use our $headers property to configure what we expect for a header in the
+    // input file.
+    $instance->setHeaders($this->headers);
+    // Configure the expected number of columns and set it to be strict.
```
Comment (laceysanderson) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php:304]: Same comment regarding strict.

**Review by laceysanderson — CHANGES_REQUESTED** [review]
✅ Code review --overall the code looks good although some issues came up in manual testing.
  - ❌ We should not be using strict on the number of columns
  - ❌ Label should be "Research Experiment" not "Project/Experiment" in the form
  - 🕐 Empty file is caught by validation but the UI response is confusing/wrong (see manual testing for screenshots). This will be fixed in #155.

## Automated testing

- [x] Missing a scenario where the are no validation errors. This would cover the formSubmit() and lines 1022-1023 in processValidationMessages().
- [x] Missing a scenario where the form already has a file + validation and the user resubmits. This would cover lines 687-689 in the formValidate().
- [x] Not full coverage of the process messages (no need to improve though as this will change when we move these methods into the validators themselves.

Screenshot 2025-04-10 at 12 34 31 PM

## Manual testing

✅ Catches non supplied project or genus --form won't submit.
✅ Catches provided project and genus that are not configured to work together
✅ Catches when provided project and genus are not linked.
PR150-genusProjectNotLinked

✅ Catches improperly delimited row (both header and data line)
PR150-improperly_delimited_header_row

✅ Catches improperly delimited data row when header is fine.
PR150-improperly_delimited_data_row

✅ Catches incorrect header
PR150-incorrect_header_with_data

✅ Catches missing required cell value (e.g. replicate)
PR150-empty_cell_after_empty_line

❌ It does catch that a file with only a header is not okay BUT the UI provides both an error that the import was not successful AND a green success header for stage 1. Plus Stage 1 is collapsed so you don't see the validation window 🙈  The first screenshot is what I see first and the second shows that the validation window once I manually expand the stage 1 accordion.
PR150-empty_data_row
PR150-empty_data_row-expanded

**Comment by laceysanderson** [comment]
I've moved the following to its own issue #155 and it will be fixed there.

> ❌ It does catch that a file with only a header is not okay BUT the UI provides both an error that the import was not successful AND a green success header for stage 1. Plus Stage 1 is collapsed so you don't see the validation window 🙈 The first screenshot is what I see first and the second shows that the validation window once I manually expand the stage 1 accordion.

File: trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php [hunk 3]
```diff
@@ -0,0 +1,789 @@
...
+   *       - 'source': indicates the location of the test file fixture relative
+   *         to a module. A source of 'trait' points to phenotypes module
+   *         fixture whereas a source of 'share' refers to the fixtures in
+   *         phenotypes share module. Fixtures in base can be reference
+   *         by an empty string.
+   *   - An array indicating the expected validation results:
+   *     - Each key is the unique name of a feedback line provided to the UI
+   *       through processValidationMessages(). Currently, there is a feedback
+   *       line for each unique validator instance that was instantiated by the
+   *       configureValidators() method in the Traits Importer class.
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php]:
```suggestion
   *       configureValidators() method in the Share Importer.
```

File: trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php [hunk 4]
```diff
@@ -0,0 +1,789 @@
...
+   *       - 'status': [REQUIRED] One of 'pass', 'todo', or 'fail'
+   *       - 'title': [REQUIRED if 'status' = 'fail'] A string that matches the
+   *         title set in processValidationMessages() method in the Traits
+   *         Importer class for this validator instance.
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php]:
```suggestion
   *         title set in processValidationMessages() method in the Share
   *         Importer for this validator instance.
```

File: trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php [hunk 5]
```diff
@@ -0,0 +1,789 @@
...
+   *       - 'filename': the filename of the data collection file.
+   *       - 'source': idicates the location of the test file fixutre relative
+   *         to a module. A source of 'trait' points to phenotypes module
+   *         fixutre whereas a source of 'share' refers to the fixtures in
+   *         phenotypes share module. Any fixutes in base can be reference
+   *         by and empty string.
+   * @param array $expected_validator_results
+   *   An array that is keyed by the unique name of each validator instance
+   *   (these names are declared in the configureValidators() method in the
+   *   Traits Importer class). Each validator instance in the array is further
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php]:
```suggestion
   *   Share Importer). Each validator instance in the array is further
```

File: trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php [hunk 6]
```diff
@@ -0,0 +1,789 @@
...
+   *   Drupal and are not related to this module's use of validator plugins.
+   *
+   * @dataProvider provideFormInputValues
+   */
+  public function testShareImporterFormValidateStage1(
+    string $scenario,
+    array $input_values,
+    array $expected_validator_results,
+    int $expected_num_form_validation_errors,
+    bool $job_created,
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php:608]: This is missing a @param in the doc block

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 7]
```diff
@@ -743,6 +914,679 @@ public function formValidate($form, &$form_state) {
...
+          ],
+        ],
+      ],
+    ];
+
+    return $render_array;
+  }
+
+  /**
+   * Use documentation in the traits importer.
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]: It looks like this docblock still needs updating

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 8]
```diff
@@ -743,6 +914,679 @@ public function formValidate($form, &$form_state) {
     }
   }
 
+  /**
+   * Begin process validation messages.
+   */
+
+  /**
+   * Use documentation in the traits importer.
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]: Documentation needs updating

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 9]
```diff
@@ -743,6 +914,679 @@ public function formValidate($form, &$form_state) {
...
+    $items = [];
+
+    if (($validation_result['case'] == 'Invalid file id number') ||
+        ($validation_result['case'] == 'File id failed to load a file object')) {
+      $message = 'A problem occurred in between uploading the file and submitting it for validation. Please try uploading and submitting it again, or contact your administrator if the problem persists.';
+
+      // Get the fid of the uploaded file.
+      $fid = $validation_result['failedItems']['fid'];
+      // Log a message for the administrator to help with debugging the issue.
+      $this->logger->info("The user $username uploaded a file with FID $fid using the Traits Importer, but could not import it as something is wrong with the filename/FID. More specifically, the case message '" . $validation_result['case'] . "' was reported.");
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]:
```suggestion
      $this->logger->info("The user $username uploaded a file with FID $fid using the Pheno Share Importer, but could not import it as something is wrong with the filename/FID. More specifically, the case message '" . $validation_result['case'] . "' was reported.");
```

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 10]
```diff
@@ -743,6 +914,679 @@ public function formValidate($form, &$form_state) {
...
+            ($validation_result['case'] == 'Unsupported file mime type and unsupported extension')) {
+      $message = "The type of file uploaded is not supported by this importer. Please ensure your file has one of the supported file extensions and was saved using software that supports that type of file. For example, a 'tsv' file should be saved as such by a spreadsheet editor such as Microsoft Excel.";
+      // Give more info to the user AND log a message to the administrator using
+      // these failed items:
+      $file_mime = $validation_result['failedItems']['mime'];
+      $file_extension = $validation_result['failedItems']['extension'];
+      $items = [
+        "The file extension indicates the file is \"$file_extension\" but our system detected the file is of type \"$file_mime\"",
+      ];
+      $this->logger->info("The user $username uploaded a file to the Traits Importer with file extension \"$file_extension\" and mime type \"$file_mime\"");
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]:
```suggestion
      $this->logger->info("The user $username uploaded a file to the Pheno Share Importer with file extension \"$file_extension\" and mime type \"$file_mime\"");
```

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 11]
```diff
@@ -743,6 +914,679 @@ public function formValidate($form, &$form_state) {
...
+    }
+    elseif ($validation_result['case'] == 'Data file cannot be opened') {
+      $message = 'The file provided could not be opened. Please contact your administrator for help.';
+      $filename = $validation_result['failedItems']['filename'];
+      $fid = $validation_result['failedItems']['fid'];
+      $items = [
+        'Filename: ' . $filename,
+      ];
+      // Log more info for the administrator.
+      $this->logger->info("The user $username uploaded a file with FID $fid using the Traits Importer, but the file could not be opened using \'@fopen\'. Filename was '$filename'.");
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]:
```suggestion
      $this->logger->info("The user $username uploaded a file with FID $fid using the Pheno Share Importer, but the file could not be opened using \'@fopen\'. Filename was '$filename'.");
```

**Review by carolyncaron — CHANGES_REQUESTED** [review]
The following is my code review - mostly suggestions to change relics from the traits Importer. 😉  I've done some manual testing (and so far so good) but will revisit with a proper review when I can dedicate more time.

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php (hunk 7 above)
Comment (carolyncaron) [reply trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]: Added in commit [4b785ea](https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/150/commits/4b785eaefb5ca66669a21a13bb4a51aaaa3de283)

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php (hunk 8 above)
Comment (carolyncaron) [reply trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]: Added in commit [4e28652](https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/150/commits/4e28652a18937f6a9e322c4d631c03afcf38e217)

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 12]
```diff
@@ -743,6 +914,721 @@ public function formValidate($form, &$form_state) {
...
+   *   - If the case string returned by the validator is not recognized.
+   */
+  public function processProjectGenusMatchFailures(array $validation_result) {
+
+    // Check the format of the validation_result parameter.
+    $this->checkValidationStatusArray($validation_result, 'ProjectGenusMatch');
+
+    // Check for one of the expected cases.
+    if ($validation_result['case'] == 'Project does not exist') {
+      $message = 'The project provided does not exist. Please contact your administrator to have this added.';
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]: Messages being displayed to the user should not mention project, but Research Experiment instead.
```suggestion
      $message = 'The selected Research Experiment does not exist. Please contact your administrator to have this added.';
```

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 13]
```diff
@@ -743,6 +914,721 @@ public function formValidate($form, &$form_state) {
...
+      $item = $validation_result['failedItems']['project_provided'];
+    }
+    elseif ($validation_result['case'] == 'Project has no genus set and could not compare with the genus provided') {
+      $message = 'The project provided does not have a genus paired to it. Please contact your administrator to have this setup.';
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]:
```suggestion
      $message = 'The selected Research Experiment does not have a genus paired to it. Please contact your administrator to have this set up.';
```

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 14]
```diff
@@ -743,6 +914,721 @@ public function formValidate($form, &$form_state) {
...
+      $item = $validation_result['failedItems']['genus_provided'];
+    }
+    elseif ($validation_result['case'] == 'Genus does not match the genus set to the project') {
+      $message = 'The genus selected does not match the genus set to the project. Please contact your administrator to have this set up.';
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]:
```suggestion
      $message = 'The selected genus has not been paired to the selected Research Experiment. Please select a paired genus or contact your administrator if you think one is missing.';
```

**Review by carolyncaron — CHANGES_REQUESTED** [review]

File: trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php [hunk 15]
```diff
@@ -743,6 +914,721 @@ public function formValidate($form, &$form_state) {
...
+   *     - 'details': A render array that will display details of any failures
+   *       to guide the user to fix problems with their input file. The type of
+   *       render array depends on the validator, but the most common types are
+   *       item list and table.
+   */
+  public function processValidationMessages($failures) {
+
+    $messages = [
+      'project_genus_match' => [
+        'title' => 'Project exists and project-genus match the genus provided',
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/src/Plugin/TripalImporter/TripalCultivatePhenoShareImporter.php]:
```suggestion
        'title' => 'Research Experiment exists and has been configured with selected genus',
```

File: trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php [hunk 16]
```diff
@@ -0,0 +1,789 @@
...
+          'project' => '',
+          'genus' => self::TEST_GENUS,
+          'file' => [
+            'filename' => 'empty_data_row.tsv',
+            'source' => 'share',
+          ],
+        ],
+        [
+          'project_genus_match' => [
+            'title' => 'Project exists and project-genus match the genus provided',
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php]:
```suggestion
            'title' => 'Research Experiment exists and has been configured with selected genus',
```

File: trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php [hunk 17]
```diff
@@ -0,0 +1,789 @@
...
+          'project' => 'A spurious project',
+          'genus' => self::TEST_GENUS,
+          'file' => [
+            'filename' => 'empty_data_row.tsv',
+            'source' => 'share',
+          ],
+        ],
+        [
+          'project_genus_match' => [
+            'title' => 'Project exists and project-genus match the genus provided',
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php]:
```suggestion
            'title' => 'Research Experiment exists and has been configured with selected genus',
```

File: trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php [hunk 18]
```diff
@@ -0,0 +1,789 @@
...
+
+    $this->assertEquals(
+      $job_created,
+      !empty($tripal_jobs),
+      'A failed import due to validation error that did not submit should not create a job request in scenario: $scenario.'
+    );
+  }
+
+  /**
+   * Test re-upload while with previous failed upload attempt.
```
Comment (carolyncaron) [inline trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php]:
```suggestion
   * Test re-upload after previous failed upload attempt.
```

**Review by carolyncaron — CHANGES_REQUESTED** [review]
### Manual Testing

This went really well! I did all the same test cases that Lacey did, and they all worked for me including the case with a header in the file but no data (I assume this was fixed by Reynold in a later commit). This is what the form now looks like:

Screenshot 2025-04-30 at 11 37 59 AM

----------------

I tried an additional case of **multiple** genus paired to a single Research Experiment. To test this, I created 2 organisms with different genus, and tried running the following in PHP Execute:
```
$m = \Drupal::service('trpcultivate_phenotypes.genus_project');
$m->setGenusToProject(1, 'Lens', FALSE);
$m->setGenusToProject(1, 'Tripalus', FALSE);
```
I explicitly used `FALSE` as the third parameter to prevent replacing the first genus:
Screenshot 2025-04-30 at 11 45 12 AM

The result is:
- ProjectGenusMatch validation passes for genus `Tripalus`
- ProjectGenusMatch validation fails for genus `Lens` (error is: `The genus selected does not match the genus set to the project. Please contact your administrator to have this set up.`)

I think this is most likely a bug in one or both methods in `TripalCultivatePhenotypesGenusProjectService.php`, which isn't in the scope of this PR, so I will make a new issue for it here: #156 

---------------
Last thing that jumped out to me, is the description for Genus on the form needs updating:
Screenshot 2025-04-30 at 11 54 39 AM
Perhaps something like:
```
Select a genus that has been configured with the selected Research Experiment.
```

Side note: We may want to update this listing to only show configured genus that have been paired to the RE. Right now from my understanding, it lists all genus that have been configured for the module (possibly another task for the above issue?).

File: trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php (hunk 6 above)
Comment (laceysanderson) [reply trpcultivate_phenoshare/tests/src/Kernel/TripalImporter/ShareImporterFormValidateTest.php:608]: This should be resolved in commit 21b7f351c5366cbb3a12ddab1568b84b7172a8cc. Specifically,

```
   * @param bool $job_created
   *   Indicates whether we expect a job to be created when the form is
   *   submitted. Specifically, if TRUE then submission should have been
   *   successful and a job should have been submitted; if FALSE then it
   *   should have been blocked in validation and no job should exist.
```

**Comment by laceysanderson** [comment]
Improved the genus description in commit e11e198b9723d41138d94825522b6d5220339ee0 in response to 

> Last thing that jumped out to me, is the description for Genus on the form needs updating:
> Screenshot 2025-04-30 at 11 54 39 AM
> Perhaps something like:
> ```
> Select a genus that has been configured with the selected Research Experiment.
> ```

The new description is shown here
Screenshot 2025-05-08 at 9 56 13 AM

**Review by laceysanderson — DISMISSED** [review]
I have confirmed that this PR also fixes Issue #155 which will now be closed when this PR is merged.

On that note, I have tested again and done a final code read through. I believe this is ready to merge! @carolyncaron can you take a quick look at my response to your last couple of suggestions?

**Review by carolyncaron — DISMISSED** [review]
Assuming that tests pass, this looks ready to merge! 🎉

**Review by laceysanderson — APPROVED** [review]
